import org.scalajs.dom.experimental.deviceorientation.{DeviceMotionEvent, DeviceOrientationEvent}
import org.scalajs.dom.raw._
import slinky.core.ExternalComponent
import slinky.core.annotations.react
import typings.stdLib.{ErrorEventHandler, MSGestureEvent, MSPointerEvent, PageTransitionEvent}

import scala.scalajs.js
import scala.scalajs.js.annotation.JSImport
import scala.scalajs.js.|

@JSImport("react-event-listener", JSImport.Default)
@js.native
object ReactEventListener extends js.Object {
  def withOptions[T](handler: js.Function1[T, _], options: EventOptions): js.Function1[T, _] = js.native
}

@react object EventListener extends ExternalComponent {

  case class Props(oNmsPointerUp: Option[MSPointerEvent => Unit] = None,
                   oNmsPointerUpCapture: Option[MSPointerEvent => Unit] = None,
                   onAbort: Option[Event => Unit] = None,
                   onAbortCapture: Option[Event => Unit] = None,
                   onAfterPrint: Option[Event => Unit] = None,
                   onAfterPrintCapture: Option[Event => Unit] = None,
                   onBeforePrint: Option[Event => Unit] = None,
                   onBeforePrintCapture: Option[Event => Unit] = None,
                   onBeforeUnload: Option[BeforeUnloadEvent => Unit] = None,
                   onBeforeUnloadCapture: Option[BeforeUnloadEvent => Unit] = None,
                   onBlur: Option[FocusEvent => Unit] = None,
                   onBlurCapture: Option[FocusEvent => Unit] = None,
                   onCanPlay: Option[Event => Unit] = None,
                   onCanPlayCapture: Option[Event => Unit] = None,
                   onCanPlayThrough: Option[Event => Unit] = None,
                   onCanPlayThroughCapture: Option[Event => Unit] = None,
                   onChange: Option[Event => Unit] = None,
                   onChangeCapture: Option[Event => Unit] = None,
                   onClick: Option[MouseEvent => Unit] = None,
                   onClickCapture: Option[MouseEvent => Unit] = None,
                   onCompassNeedsCalibration: Option[Event => Unit] = None,
                   onCompassNeedsCalibrationCapture: Option[Event => Unit] = None,
                   onContextMenu: Option[PointerEvent => Unit] = None,
                   onContextMenuCapture: Option[PointerEvent => Unit] = None,
                   onDblClick: Option[MouseEvent => Unit] = None,
                   onDblClickCapture: Option[MouseEvent => Unit] = None,
                   onDeviceMotion: Option[DeviceMotionEvent => Unit] = None,
                   onDeviceMotionCapture: Option[DeviceMotionEvent => Unit] = None,
                   onDeviceOrientation: Option[DeviceOrientationEvent => Unit] = None,
                   onDeviceOrientationCapture: Option[DeviceOrientationEvent => Unit] = None,
                   onDrag: Option[DragEvent => Unit] = None,
                   onDragCapture: Option[DragEvent => Unit] = None,
                   onDragEnd: Option[DragEvent => Unit] = None,
                   onDragEndCapture: Option[DragEvent => Unit] = None,
                   onDragEnter: Option[DragEvent => Unit] = None,
                   onDragEnterCapture: Option[DragEvent => Unit] = None,
                   onDragLeave: Option[DragEvent => Unit] = None,
                   onDragLeaveCapture: Option[DragEvent => Unit] = None,
                   onDragOver: Option[DragEvent => Unit] = None,
                   onDragOverCapture: Option[DragEvent => Unit] = None,
                   onDragStart: Option[DragEvent => Unit] = None,
                   onDragStartCapture: Option[DragEvent => Unit] = None,
                   onDrop: Option[DragEvent => Unit] = None,
                   onDropCapture: Option[DragEvent => Unit] = None,
                   onDurationChange: Option[Event => Unit] = None,
                   onDurationChangeCapture: Option[Event => Unit] = None,
                   onEmptied: Option[Event => Unit] = None,
                   onEmptiedCapture: Option[Event => Unit] = None,
                   onEnded: Option[Event => Unit] = None,
                   onEndedCapture: Option[Event => Unit] = None,
                   onError: Option[ErrorEventHandler] = None,
                   onErrorCapture: Option[ErrorEventHandler] = None,
                   onFocus: Option[FocusEvent => Unit] = None,
                   onFocusCapture: Option[FocusEvent => Unit] = None,
                   onHashChange: Option[HashChangeEvent => Unit] = None,
                   onHashChangeCapture: Option[HashChangeEvent => Unit] = None,
                   onInput: Option[Event => Unit] = None,
                   onInputCapture: Option[Event => Unit] = None,
                   onKeyDown: Option[KeyboardEvent => Unit] = None,
                   onKeyDownCapture: Option[KeyboardEvent => Unit] = None,
                   onKeyPress: Option[KeyboardEvent => Unit] = None,
                   onKeyPressCapture: Option[KeyboardEvent => Unit] = None,
                   onKeyUp: Option[KeyboardEvent => Unit] = None,
                   onKeyUpCapture: Option[KeyboardEvent => Unit] = None,
                   onLoad: Option[Event => Unit] = None,
                   onLoadCapture: Option[Event => Unit] = None,
                   onLoadStart: Option[Event => Unit] = None,
                   onLoadStartCapture: Option[Event => Unit] = None,
                   onLoadedData: Option[Event => Unit] = None,
                   onLoadedDataCapture: Option[Event => Unit] = None,
                   onLoadedMetadata: Option[Event => Unit] = None,
                   onLoadedMetadataCapture: Option[Event => Unit] = None,
                   onMessage: Option[MessageEvent => Unit] = None,
                   onMessageCapture: Option[MessageEvent => Unit] = None,
                   onMouseDown: Option[MouseEvent => Unit] = None,
                   onMouseDownCapture: Option[MouseEvent => Unit] = None,
                   onMouseEnter: Option[MouseEvent => Unit] = None,
                   onMouseEnterCapture: Option[MouseEvent => Unit] = None,
                   onMouseLeave: Option[MouseEvent => Unit] = None,
                   onMouseLeaveCapture: Option[MouseEvent => Unit] = None,
                   onMouseMove: Option[MouseEvent => Unit] = None,
                   onMouseMoveCapture: Option[MouseEvent => Unit] = None,
                   onMouseOut: Option[MouseEvent => Unit] = None,
                   onMouseOutCapture: Option[MouseEvent => Unit] = None,
                   onMouseOver: Option[MouseEvent => Unit] = None,
                   onMouseOverCapture: Option[MouseEvent => Unit] = None,
                   onMouseUp: Option[MouseEvent => Unit] = None,
                   onMouseUpCapture: Option[MouseEvent => Unit] = None,
                   onMouseWheel: Option[WheelEvent => Unit] = None,
                   onMouseWheelCapture: Option[WheelEvent => Unit] = None,
                   onMsGestureChange: Option[MSGestureEvent => Unit] = None,
                   onMsGestureChangeCapture: Option[MSGestureEvent => Unit] = None,
                   onMsGestureDoubleTap: Option[MSGestureEvent => Unit] = None,
                   onMsGestureDoubleTapCapture: Option[MSGestureEvent => Unit] = None,
                   onMsGestureEnd: Option[MSGestureEvent => Unit] = None,
                   onMsGestureEndCapture: Option[MSGestureEvent => Unit] = None,
                   onMsGestureHold: Option[MSGestureEvent => Unit] = None,
                   onMsGestureHoldCapture: Option[MSGestureEvent => Unit] = None,
                   onMsGestureStart: Option[MSGestureEvent => Unit] = None,
                   onMsGestureStartCapture: Option[MSGestureEvent => Unit] = None,
                   onMsGestureTap: Option[MSGestureEvent => Unit] = None,
                   onMsGestureTapCapture: Option[MSGestureEvent => Unit] = None,
                   onMsInertiaStart: Option[MSGestureEvent => Unit] = None,
                   onMsInertiaStartCapture: Option[MSGestureEvent => Unit] = None,
                   onMsPointerCancel: Option[MSPointerEvent => Unit] = None,
                   onMsPointerCancelCapture: Option[MSPointerEvent => Unit] = None,
                   onMsPointerDown: Option[MSPointerEvent => Unit] = None,
                   onMsPointerDownCapture: Option[MSPointerEvent => Unit] = None,
                   onMsPointerEnter: Option[MSPointerEvent => Unit] = None,
                   onMsPointerEnterCapture: Option[MSPointerEvent => Unit] = None,
                   onMsPointerLeave: Option[MSPointerEvent => Unit] = None,
                   onMsPointerLeaveCapture: Option[MSPointerEvent => Unit] = None,
                   onMsPointerMove: Option[MSPointerEvent => Unit] = None,
                   onMsPointerMoveCapture: Option[MSPointerEvent => Unit] = None,
                   onMsPointerOut: Option[MSPointerEvent => Unit] = None,
                   onMsPointerOutCapture: Option[MSPointerEvent => Unit] = None,
                   onMsPointerOver: Option[MSPointerEvent => Unit] = None,
                   onMsPointerOverCapture: Option[MSPointerEvent => Unit] = None,
                   onOffline: Option[Event => Unit] = None,
                   onOfflineCapture: Option[Event => Unit] = None,
                   onOnline: Option[Event => Unit] = None,
                   onOnlineCapture: Option[Event => Unit] = None,
                   onOrientationChange: Option[Event => Unit] = None,
                   onOrientationChangeCapture: Option[Event => Unit] = None,
                   onPageHide: Option[PageTransitionEvent => Unit] = None,
                   onPageHideCapture: Option[PageTransitionEvent => Unit] = None,
                   onPageShow: Option[PageTransitionEvent => Unit] = None,
                   onPageShowCapture: Option[PageTransitionEvent => Unit] = None,
                   onPause: Option[Event => Unit] = None,
                   onPauseCapture: Option[Event => Unit] = None,
                   onPlay: Option[Event => Unit] = None,
                   onPlayCapture: Option[Event => Unit] = None,
                   onPlaying: Option[Event => Unit] = None,
                   onPlayingCapture: Option[Event => Unit] = None,
                   // Global events
                   onPointerCancel: Option[PointerEvent => Unit] = None,
                   onPointerCancelCapture: Option[PointerEvent => Unit] = None,
                   onPointerDown: Option[PointerEvent => Unit] = None,
                   onPointerDownCapture: Option[PointerEvent => Unit] = None,
                   onPointerEnter: Option[PointerEvent => Unit] = None,
                   onPointerEnterCapture: Option[PointerEvent => Unit] = None,
                   onPointerLeave: Option[PointerEvent => Unit] = None,
                   onPointerLeaveCapture: Option[PointerEvent => Unit] = None,
                   onPointerMove: Option[PointerEvent => Unit] = None,
                   onPointerMoveCapture: Option[PointerEvent => Unit] = None,
                   onPointerOut: Option[PointerEvent => Unit] = None,
                   onPointerOutCapture: Option[PointerEvent => Unit] = None,
                   onPointerOver: Option[PointerEvent => Unit] = None,
                   onPointerOverCapture: Option[PointerEvent => Unit] = None,
                   onPointerUp: Option[PointerEvent => Unit] = None,
                   onPointerUpCapture: Option[PointerEvent => Unit] = None,
                   onPopState: Option[PopStateEvent => Unit] = None,
                   onPopStateCapture: Option[PopStateEvent => Unit] = None,
                   onProgress: Option[ProgressEvent => Unit] = None,
                   onProgressCapture: Option[ProgressEvent => Unit] = None,
                   onRateChange: Option[Event => Unit] = None,
                   onRateChangeCapture: Option[Event => Unit] = None,
                   onReadyStateChange: Option[ProgressEvent => Unit] = None,
                   onReadyStateChangeCapture: Option[ProgressEvent => Unit] = None,
                   onReset: Option[Event => Unit] = None,
                   onResetCapture: Option[Event => Unit] = None,
                   onResize: Option[UIEvent => Unit] = None,
                   onResizeCapture: Option[UIEvent => Unit] = None,
                   onScroll: Option[UIEvent => Unit] = None,
                   onScrollCapture: Option[UIEvent => Unit] = None,
                   onSeeked: Option[Event => Unit] = None,
                   onSeekedCapture: Option[Event => Unit] = None,
                   onSeeking: Option[Event => Unit] = None,
                   onSeekingCapture: Option[Event => Unit] = None,
                   onSelect: Option[UIEvent => Unit] = None,
                   onSelectCapture: Option[UIEvent => Unit] = None,
                   onSelectionChange: Option[Event => Unit] = None,
                   onSelectionChangeCapture: Option[Event => Unit] = None,
                   onStalled: Option[Event => Unit] = None,
                   onStalledCapture: Option[Event => Unit] = None,
                   onStorage: Option[StorageEvent => Unit] = None,
                   onStorageCapture: Option[StorageEvent => Unit] = None,
                   onSubmit: Option[Event => Unit] = None,
                   onSubmitCapture: Option[Event => Unit] = None,
                   onSuspend: Option[Event => Unit] = None,
                   onSuspendCapture: Option[Event => Unit] = None,
                   onTimeUpdate: Option[Event => Unit] = None,
                   onTimeUpdateCapture: Option[Event => Unit] = None,
                   onTouchCancel: Option[js.Any] = None,
                   onTouchCancelCapture: Option[js.Any] = None,
                   onTouchEnd: Option[js.Any] = None,
                   onTouchEndCapture: Option[js.Any] = None,
                   onTouchMove: Option[js.Any] = None,
                   onTouchMoveCapture: Option[js.Any] = None,
                   onTouchStart: Option[js.Any] = None,
                   onTouchStartCapture: Option[js.Any] = None,
                   onUnload: Option[Event => Unit] = None,
                   onUnloadCapture: Option[Event => Unit] = None,
                   onVolumeChange: Option[Event => Unit] = None,
                   onVolumeChangeCapture: Option[Event => Unit] = None,
                   onWaiting: Option[Event => Unit] = None,
                   onWaitingCapture: Option[Event => Unit] = None,
                   onWheel: Option[WheelEvent => Unit] = None,
                   onWheelCapture: Option[WheelEvent => Unit] = None,
                   target: Window | Document | String)

  override val component = ReactEventListener
}

@js.native
trait EventOptions extends js.Object {
  val capture: js.UndefOr[Boolean] = js.native
  val passive: js.UndefOr[Boolean] = js.native
}